name: CD

on:
  push:
    tags: [ 'v**' ]
  workflow_dispatch:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python_version: 3.10.0
      - name: Run all checks
        run: poetry run task checks
  
  build-unix:
    name: "Build - Unix"
    needs: checks
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python_version: 3.10.0
      - name: Build
        run: poetry run task build
      - name: Upload builds
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build-unix
          path: ./dist/*.zip
  
  build-macos:
    name: "Build - MacOS"
    needs: checks
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python_version: 3.10.0
      - name: Build
        run: poetry run task build
      - name: Upload builds
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build-macos
          path: ./dist/*.zip
  
  build-win:
    name: "Build - Windows"
    needs: checks
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          python_version: 3.10.0
      - name: Build
        run: poetry run task build
      - name: Upload builds
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build-win
          path: ./dist/*.zip
  
  release:
    name: Release
    needs: [build-unix, build-macos, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Get builds
        uses: actions/download-artifact@v2.1.0
        with:
          path: ./dist
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./dist/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
