# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.10.0
          architecture: x64
      - name: setup poetry
        uses: Gr1N/setup-poetry@v7
      - name: install package
        run: poetry install
      - run: poetry run task checks
